/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    unoptimized: true,
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**', // Allows external images from Supabase/Web
      },
    ],
  },
  async redirects() {
    return [
      {
        source: '/consoles/brand/:slug',
        destination: '/fabricators/:slug',
        permanent: true,
      },
      { source: '/consoles/k59', destination: '/consoles/kinhank-k59', permanent: true },
      { source: '/consoles/smart-pro', destination: '/consoles/trimui-smart-pro', permanent: true },
      { source: '/consoles/loki', destination: '/consoles/ayn-loki', permanent: true },
      { source: '/consoles/pocket', destination: '/consoles/analogue-pocket', permanent: true },
      { source: '/consoles/loki-max', destination: '/consoles/ayn-loki-max', permanent: true },
      { source: '/consoles/loki-zero', destination: '/consoles/ayn-loki-zero', permanent: true },
      { source: '/consoles/loki-mini-pro', destination: '/consoles/ayn-loki-mini-pro', permanent: true },
      { source: '/consoles/pocket-micro', destination: '/consoles/ayaneo-pocket-micro', permanent: true },
      { source: '/consoles/a30', destination: '/consoles/miyoo-a30', permanent: true },
      { source: '/consoles/smart-pro-s', destination: '/consoles/trimui-smart-pro-s', permanent: true },
      { source: '/consoles/pocket-4', destination: '/consoles/retroid-pocket-4', permanent: true },
      { source: '/consoles/pocket-vert', destination: '/consoles/ayaneo-pocket-vert', permanent: true },
      { source: '/consoles/pocket-s-mini', destination: '/consoles/ayaneo-pocket-s-mini', permanent: true },
      { source: '/consoles/sf2000', destination: '/consoles/data-frog-sf2000', permanent: true },
      { source: '/consoles/pocket-mini', destination: '/consoles/retroid-pocket-mini', permanent: true },
      { source: '/consoles/rg-34xxsp', destination: '/consoles/anbernic-rg-34xxsp', permanent: true },
      { source: '/consoles/mini-plus', destination: '/consoles/miyoo-mini-plus', permanent: true },
      { source: '/consoles/odin-2-portal', destination: '/consoles/ayn-odin-2-portal', permanent: true },
      { source: '/consoles/rog-ally', destination: '/consoles/asus-rog-ally', permanent: true },
      { source: '/consoles/switch', destination: '/consoles/nintendo-switch', permanent: true },
      { source: '/consoles/pocket-2s', destination: '/consoles/retroid-pocket-2s', permanent: true },
      { source: '/consoles/rg-35xxsp', destination: '/consoles/anbernic-rg-35xxsp', permanent: true },
      { source: '/consoles/pocket-1', destination: '/consoles/retroid-pocket-1', permanent: true },
      { source: '/consoles/pocket-3', destination: '/consoles/retroid-pocket-3', permanent: true },
      { source: '/consoles/pocket-g2', destination: '/consoles/retroid-pocket-g2', permanent: true },
      { source: '/consoles/pocket-classic', destination: '/consoles/retroid-pocket-classic', permanent: true },
      { source: '/consoles/thor', destination: '/consoles/ayn-thor', permanent: true },
      { source: '/consoles/rg-28xx', destination: '/consoles/anbernic-rg-28xx', permanent: true },
      { source: '/consoles/pocket-2', destination: '/consoles/retroid-pocket-2', permanent: true },
      { source: '/consoles/rg-476h', destination: '/consoles/anbernic-rg-476h', permanent: true },
      { source: '/consoles/pocket-5', destination: '/consoles/retroid-pocket-5', permanent: true },
      { source: '/consoles/rg-351m', destination: '/consoles/anbernic-rg-351m', permanent: true },
      { source: '/consoles/rg-cube', destination: '/consoles/anbernic-rg-cube', permanent: true },
      { source: '/consoles/rg-477v', destination: '/consoles/anbernic-rg-477v', permanent: true },
      { source: '/consoles/rg-40xxv', destination: '/consoles/anbernic-rg-40xxv', permanent: true },
      { source: '/consoles/pocket-2-plus', destination: '/consoles/retroid-pocket-2-plus', permanent: true },
      { source: '/consoles/rg-vita', destination: '/consoles/anbernic-rg-vita', permanent: true },
      { source: '/consoles/pocket-flip-2', destination: '/consoles/retroid-pocket-flip-2', permanent: true },
      { source: '/consoles/mini-flip', destination: '/consoles/miyoo-mini-flip', permanent: true },
      { source: '/consoles/rg-35xx-plus', destination: '/consoles/anbernic-rg-35xx-plus', permanent: true },
      { source: '/consoles/pocket-mini-v2', destination: '/consoles/retroid-pocket-mini-v2', permanent: true },
      { source: '/consoles/rg-35xxh', destination: '/consoles/anbernic-rg-35xxh', permanent: true },
      { source: '/consoles/odin-lite', destination: '/consoles/ayn-odin-lite', permanent: true },
      { source: '/consoles/rgb30', destination: '/consoles/powkiddy-rgb30', permanent: true },
      { source: '/consoles/pocket-6', destination: '/consoles/retroid-pocket-6', permanent: true },
      { source: '/consoles/odin-2-mini', destination: '/consoles/ayn-odin-2-mini', permanent: true },
      { source: '/consoles/odin-2', destination: '/consoles/ayn-odin-2', permanent: true },
      { source: '/consoles/pocket-flip', destination: '/consoles/retroid-pocket-flip', permanent: true },
      { source: '/consoles/pocket-3-plus', destination: '/consoles/retroid-pocket-3-plus', permanent: true },
      { source: '/consoles/rg-350p', destination: '/consoles/anbernic-rg-350p', permanent: true },
      { source: '/consoles/air-x', destination: '/consoles/mangmi-air-x', permanent: true },
      { source: '/consoles/pocket-max', destination: '/consoles/mangmi-pocket-max', permanent: true },
      { source: '/consoles/rg-ds', destination: '/consoles/anbernic-rg-ds', permanent: true },
      { source: '/consoles/odin', destination: '/consoles/ayn-odin', permanent: true },
      { source: '/consoles/odin-3', destination: '/consoles/ayn-odin-3', permanent: true },
      { source: '/consoles/steam-deck', destination: '/consoles/valve-steam-deck', permanent: true },
      { source: '/consoles/steam-deck-oled', destination: '/consoles/valve-steam-deck-oled', permanent: true },
      { source: '/consoles/pocket-s2', destination: '/consoles/ayaneo-pocket-s2', permanent: true },
      { source: '/consoles/pocket-air-mini', destination: '/consoles/ayaneo-pocket-air-mini', permanent: true },
      { source: '/consoles/pocket-ds', destination: '/consoles/ayaneo-pocket-ds', permanent: true },
      { source: '/consoles/pocket-s2-pro', destination: '/consoles/ayaneo-pocket-s2-pro', permanent: true },
      { source: '/consoles/pocket-dmg', destination: '/consoles/ayaneo-pocket-dmg', permanent: true },
      { source: '/consoles/pocket-micro-classic', destination: '/consoles/ayaneo-pocket-micro-classic', permanent: true },
      { source: '/consoles/pocket-ace', destination: '/consoles/ayaneo-pocket-ace', permanent: true },
      { source: '/consoles/pocket-evo', destination: '/consoles/ayaneo-pocket-evo', permanent: true },
      { source: '/consoles/pocket-air', destination: '/consoles/ayaneo-pocket-air', permanent: true },
      { source: '/consoles/pocket-s-1080p', destination: '/consoles/ayaneo-pocket-s-1080p', permanent: true },
      { source: '/consoles/pocket-fit', destination: '/consoles/konkr-pocket-fit', permanent: true },
      { source: '/consoles/smart-brick', destination: '/consoles/trimui-smart-brick', permanent: true },
      { source: '/consoles/flip', destination: '/consoles/miyoo-flip', permanent: true },
      { source: '/consoles/pocket-s-1440p', destination: '/consoles/ayaneo-pocket-s-1440p', permanent: true },
      { source: '/consoles/rg-351p', destination: '/consoles/anbernic-rg-351p', permanent: true },
      { source: '/consoles/rg-351v', destination: '/consoles/anbernic-rg-351v', permanent: true },
      { source: '/consoles/rg-351mp', destination: '/consoles/anbernic-rg-351mp', permanent: true },
      { source: '/consoles/rg-405m', destination: '/consoles/anbernic-rg-405m', permanent: true },
      { source: '/consoles/rg-405v', destination: '/consoles/anbernic-rg-405v', permanent: true },
      { source: '/consoles/mini', destination: '/consoles/miyoo-mini', permanent: true },
      { source: '/consoles/rg-350', destination: '/consoles/anbernic-rg-350', permanent: true },
      { source: '/consoles/rg-350m', destination: '/consoles/anbernic-rg-350m', permanent: true },
    ]
  },
};

export default nextConfig;
