
import * as React from 'react';
import { useEffect, useState } from 'react';
import { addToCollection, fetchUserCollection, removeFromCollection, retroAuth } from '../services/geminiService';
import { UserCollectionItem } from '../types';
import Button from './Button';
import { useNavigate } from 'react-router-dom';

interface CollectionToggleProps {
    itemId: string;
    itemType: 'GAME' | 'CONSOLE';
    itemName: string;
    itemImage?: string;
}

const CollectionToggle: React.FC<CollectionToggleProps> = ({ itemId, itemType, itemName, itemImage }) => {
    const [status, setStatus] = useState<'OWN' | 'WANT' | null>(null);
    const [loading, setLoading] = useState(false);
    const navigate = useNavigate();

    useEffect(() => {
        const checkStatus = async () => {
            const user = await retroAuth.getUser();
            if (user) {
                const collection = await fetchUserCollection();
                const item = collection.find(i => i.item_id === itemId && i.item_type === itemType);
                if (item) setStatus(item.status);
            }
        };
        checkStatus();
    }, [itemId, itemType]);

    const handleToggle = async (newStatus: 'OWN' | 'WANT') => {
        setLoading(true);
        const user = await retroAuth.getUser();
        
        if (!user) {
            navigate('/login');
            return;
        }

        if (status === newStatus) {
            // Remove
            await removeFromCollection(itemId);
            setStatus(null);
        } else {
            // Add or Update
            const newItem: UserCollectionItem = {
                id: '', // Generated by DB
                user_id: '', // Handled by service
                item_id: itemId,
                item_type: itemType,
                status: newStatus,
                item_name: itemName,
                item_image: itemImage
            };
            await addToCollection(newItem);
            setStatus(newStatus);
        }
        setLoading(false);
    };

    return (
        <div className="flex gap-2">
            <Button 
                variant={status === 'OWN' ? 'primary' : 'secondary'} 
                className={`flex-1 text-xs py-1 ${status === 'OWN' ? 'bg-retro-neon/20' : ''}`}
                onClick={() => handleToggle('OWN')}
                isLoading={loading}
            >
                {status === 'OWN' ? 'IN COLLECTION' : '+ I OWN THIS'}
            </Button>
            <Button 
                variant={status === 'WANT' ? 'danger' : 'secondary'} 
                className={`flex-1 text-xs py-1 ${status === 'WANT' ? 'bg-retro-pink/20' : ''}`}
                onClick={() => handleToggle('WANT')}
                isLoading={loading}
            >
                {status === 'WANT' ? 'ON WISHLIST' : '+ I WANT THIS'}
            </Button>
        </div>
    );
};

export default CollectionToggle;
